/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt --file-name=cuda-sakgengetopt 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cuda-sakgengetopt.h"

const char *gengetopt_args_info_purpose = "Definir as opções do cuda-sak";

const char *gengetopt_args_info_usage = "Usage: mei-team_cuda-sak [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "Ficheiro de configuração do gengetopt";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "\ngrupo principal:",
  "\n Group: grupo principal\n  definição do grupo principal",
  "  -d, --device                  opção -d / -device",
  "  -e, --handleerror             Generates the CUDA error processing code",
  "  -k, --callkernel=name         Generates the code that calls kernel. Requires\n                                  the name of the kernel as paremeter",
  "  -m, --genmaps=dimension to map\n                                Generates the mapping for n-D geometries to 1-D\n                                  kernel. n should be given and should be\n                                  between 1 and 3  (possible values=\"1\",\n                                  \"2\", \"3\")",
  "  -o, --occupancy               Generates the skeleton code that uses the CUDA\n                                  6.5 occupancy API",
  "  -p, --preprocessor=arch version\n                                Generates the wrappes for preprocessor.\n                                  Requires architecture as parameter, which\n                                  must be a number greater than 1 and a\n                                  multiple of 10.",
  "  -r, --reduction               Generates the skeleton kernel code regarding\n                                  the traditional log2 N reduction algorithm.",
  "  -s, --skeleton=name of the kernel\n                                Generates the source code if a CUDA kernel\n                                  skeleton",
  "  -t, --timing                  Generates the source code used for timing the\n                                  execution of a CUDA kernel.",
  "  -u, --unified                 Generates the skeleton code that uses CUDA 6.5\n                                  unified memory API.",
  "      --about                   Displays the credits of the application.",
  "  -a, --testall                 Activates all the options that generate code.",
  "  -f, --filename=filename       Needs filename and writes output to that file",
  "      --students=all options between \"\n                                Used along with other option(to define the\n                                  output).Needs origin filename and line to\n                                  write in.",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_genmaps_values[] = {"1", "2", "3", 0}; /*< Possible values for genmaps. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->device_given = 0 ;
  args_info->handleerror_given = 0 ;
  args_info->callkernel_given = 0 ;
  args_info->genmaps_given = 0 ;
  args_info->occupancy_given = 0 ;
  args_info->preprocessor_given = 0 ;
  args_info->reduction_given = 0 ;
  args_info->skeleton_given = 0 ;
  args_info->timing_given = 0 ;
  args_info->unified_given = 0 ;
  args_info->about_given = 0 ;
  args_info->testall_given = 0 ;
  args_info->filename_given = 0 ;
  args_info->students_given = 0 ;
  args_info->grupo_principal_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->callkernel_arg = NULL;
  args_info->callkernel_orig = NULL;
  args_info->genmaps_orig = NULL;
  args_info->preprocessor_orig = NULL;
  args_info->skeleton_arg = NULL;
  args_info->skeleton_orig = NULL;
  args_info->filename_arg = NULL;
  args_info->filename_orig = NULL;
  args_info->students_arg = NULL;
  args_info->students_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->device_help = gengetopt_args_info_help[4] ;
  args_info->handleerror_help = gengetopt_args_info_help[5] ;
  args_info->callkernel_help = gengetopt_args_info_help[6] ;
  args_info->genmaps_help = gengetopt_args_info_help[7] ;
  args_info->occupancy_help = gengetopt_args_info_help[8] ;
  args_info->preprocessor_help = gengetopt_args_info_help[9] ;
  args_info->reduction_help = gengetopt_args_info_help[10] ;
  args_info->skeleton_help = gengetopt_args_info_help[11] ;
  args_info->timing_help = gengetopt_args_info_help[12] ;
  args_info->unified_help = gengetopt_args_info_help[13] ;
  args_info->about_help = gengetopt_args_info_help[14] ;
  args_info->testall_help = gengetopt_args_info_help[15] ;
  args_info->filename_help = gengetopt_args_info_help[16] ;
  args_info->students_help = gengetopt_args_info_help[17] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->callkernel_arg));
  free_string_field (&(args_info->callkernel_orig));
  free_string_field (&(args_info->genmaps_orig));
  free_string_field (&(args_info->preprocessor_orig));
  free_string_field (&(args_info->skeleton_arg));
  free_string_field (&(args_info->skeleton_orig));
  free_string_field (&(args_info->filename_arg));
  free_string_field (&(args_info->filename_orig));
  free_string_field (&(args_info->students_arg));
  free_string_field (&(args_info->students_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->device_given)
    write_into_file(outfile, "device", 0, 0 );
  if (args_info->handleerror_given)
    write_into_file(outfile, "handleerror", 0, 0 );
  if (args_info->callkernel_given)
    write_into_file(outfile, "callkernel", args_info->callkernel_orig, 0);
  if (args_info->genmaps_given)
    write_into_file(outfile, "genmaps", args_info->genmaps_orig, cmdline_parser_genmaps_values);
  if (args_info->occupancy_given)
    write_into_file(outfile, "occupancy", 0, 0 );
  if (args_info->preprocessor_given)
    write_into_file(outfile, "preprocessor", args_info->preprocessor_orig, 0);
  if (args_info->reduction_given)
    write_into_file(outfile, "reduction", 0, 0 );
  if (args_info->skeleton_given)
    write_into_file(outfile, "skeleton", args_info->skeleton_orig, 0);
  if (args_info->timing_given)
    write_into_file(outfile, "timing", 0, 0 );
  if (args_info->unified_given)
    write_into_file(outfile, "unified", 0, 0 );
  if (args_info->about_given)
    write_into_file(outfile, "about", 0, 0 );
  if (args_info->testall_given)
    write_into_file(outfile, "testall", 0, 0 );
  if (args_info->filename_given)
    write_into_file(outfile, "filename", args_info->filename_orig, 0);
  if (args_info->students_given)
    write_into_file(outfile, "students", args_info->students_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static void
reset_group_grupo_principal(struct gengetopt_args_info *args_info)
{
  if (! args_info->grupo_principal_group_counter)
    return;
  
  args_info->device_given = 0 ;
  args_info->handleerror_given = 0 ;
  args_info->callkernel_given = 0 ;
  free_string_field (&(args_info->callkernel_arg));
  free_string_field (&(args_info->callkernel_orig));
  args_info->genmaps_given = 0 ;
  free_string_field (&(args_info->genmaps_orig));
  args_info->occupancy_given = 0 ;
  args_info->preprocessor_given = 0 ;
  free_string_field (&(args_info->preprocessor_orig));
  args_info->reduction_given = 0 ;
  args_info->skeleton_given = 0 ;
  free_string_field (&(args_info->skeleton_arg));
  free_string_field (&(args_info->skeleton_orig));
  args_info->timing_given = 0 ;
  args_info->unified_given = 0 ;
  args_info->about_given = 0 ;
  args_info->testall_given = 0 ;

  args_info->grupo_principal_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (args_info->grupo_principal_group_counter == 0)
    {
      fprintf (stderr, "%s: %d options of group grupo principal were given. One is required%s.\n", prog_name, args_info->grupo_principal_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  

  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "device",	0, NULL, 'd' },
        { "handleerror",	0, NULL, 'e' },
        { "callkernel",	1, NULL, 'k' },
        { "genmaps",	1, NULL, 'm' },
        { "occupancy",	0, NULL, 'o' },
        { "preprocessor",	1, NULL, 'p' },
        { "reduction",	0, NULL, 'r' },
        { "skeleton",	1, NULL, 's' },
        { "timing",	0, NULL, 't' },
        { "unified",	0, NULL, 'u' },
        { "about",	0, NULL, 0 },
        { "testall",	0, NULL, 'a' },
        { "filename",	1, NULL, 'f' },
        { "students",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVdek:m:op:rs:tuaf:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'd':	/* opção -d / -device.  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->device_given),
              &(local_args_info.device_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "device", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* Generates the CUDA error processing code.  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->handleerror_given),
              &(local_args_info.handleerror_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "handleerror", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Generates the code that calls kernel. Requires the name of the kernel as paremeter.  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->callkernel_arg), 
               &(args_info->callkernel_orig), &(args_info->callkernel_given),
              &(local_args_info.callkernel_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "callkernel", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Generates the mapping for n-D geometries to 1-D kernel. n should be given and should be between 1 and 3.  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->genmaps_arg), 
               &(args_info->genmaps_orig), &(args_info->genmaps_given),
              &(local_args_info.genmaps_given), optarg, cmdline_parser_genmaps_values, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "genmaps", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Generates the skeleton code that uses the CUDA 6.5 occupancy API.  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->occupancy_given),
              &(local_args_info.occupancy_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "occupancy", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Generates the wrappes for preprocessor. Requires architecture as parameter, which must be a number greater than 1 and a multiple of 10..  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->preprocessor_arg), 
               &(args_info->preprocessor_orig), &(args_info->preprocessor_given),
              &(local_args_info.preprocessor_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "preprocessor", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Generates the skeleton kernel code regarding the traditional log2 N reduction algorithm..  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->reduction_given),
              &(local_args_info.reduction_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "reduction", 'r',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Generates the source code if a CUDA kernel skeleton.  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( (void *)&(args_info->skeleton_arg), 
               &(args_info->skeleton_orig), &(args_info->skeleton_given),
              &(local_args_info.skeleton_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "skeleton", 's',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Generates the source code used for timing the execution of a CUDA kernel..  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->timing_given),
              &(local_args_info.timing_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "timing", 't',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Generates the skeleton code that uses CUDA 6.5 unified memory API..  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->unified_given),
              &(local_args_info.unified_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "unified", 'u',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Activates all the options that generate code..  */
        
          if (args_info->grupo_principal_group_counter && override)
            reset_group_grupo_principal (args_info);
          args_info->grupo_principal_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->testall_given),
              &(local_args_info.testall_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "testall", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Needs filename and writes output to that file.  */
        
        
          if (update_arg( (void *)&(args_info->filename_arg), 
               &(args_info->filename_orig), &(args_info->filename_given),
              &(local_args_info.filename_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "filename", 'f',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Displays the credits of the application..  */
          if (strcmp (long_options[option_index].name, "about") == 0)
          {
          
            if (args_info->grupo_principal_group_counter && override)
              reset_group_grupo_principal (args_info);
            args_info->grupo_principal_group_counter += 1;
          
            if (update_arg( 0 , 
                 0 , &(args_info->about_given),
                &(local_args_info.about_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "about", '-',
                additional_error))
              goto failure;
          
          }
          /* Used along with other option(to define the output).Needs origin filename and line to write in..  */
          else if (strcmp (long_options[option_index].name, "students") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->students_arg), 
                 &(args_info->students_orig), &(args_info->students_given),
                &(local_args_info.students_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "students", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->grupo_principal_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group grupo principal were given. One is required%s.\n", argv[0], args_info->grupo_principal_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  


  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
